// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_sBWfNvvxZw4u9tRPPoBGux6DnXdIg7k',
    appId: '1:697493357125:web:8bbe2edc07775b1a32992c',
    messagingSenderId: '697493357125',
    projectId: 'ecommerce-app-ad6c2',
    authDomain: 'ecommerce-app-ad6c2.firebaseapp.com',
    storageBucket: 'ecommerce-app-ad6c2.appspot.com',
    measurementId: 'G-2HB41SS6PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbzMBMtpRkrOoJmiqjbykyo1FA1SWFZ5I',
    appId: '1:697493357125:android:e979488fe0c90cf232992c',
    messagingSenderId: '697493357125',
    projectId: 'ecommerce-app-ad6c2',
    storageBucket: 'ecommerce-app-ad6c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5nPZYs7DR5GzMhrisSc0hbYxtqlkA2wE',
    appId: '1:697493357125:ios:7f0bddad9272395b32992c',
    messagingSenderId: '697493357125',
    projectId: 'ecommerce-app-ad6c2',
    storageBucket: 'ecommerce-app-ad6c2.appspot.com',
    iosClientId: '697493357125-htp3bse5nougun6ono2kb0kitkmjb5da.apps.googleusercontent.com',
    iosBundleId: 'com.example.userEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5nPZYs7DR5GzMhrisSc0hbYxtqlkA2wE',
    appId: '1:697493357125:ios:7f0bddad9272395b32992c',
    messagingSenderId: '697493357125',
    projectId: 'ecommerce-app-ad6c2',
    storageBucket: 'ecommerce-app-ad6c2.appspot.com',
    iosClientId: '697493357125-htp3bse5nougun6ono2kb0kitkmjb5da.apps.googleusercontent.com',
    iosBundleId: 'com.example.userEcommerceApp',
  );
}
